<?php

use Illuminate\Database\Seeder;

class SeriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('series')->delete();
        
        \DB::table('series')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Band of Brothers',
                'synopsis' => 'The story of Easy Company of the US Army 101st Airborne division and their mission in WWII Europe from Operation Overlord through V-J Day.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTI3ODc2ODc0M15BMl5BanBnXkFtZTYwMjgzNjc3._V1_SX300.jpg',
                'actors' => 'Scott Grimes, Damian Lewis, Ron Livingston, Shane Taylor',
                'producer' => 'N/A',
                'duration_pattern' => 70,
                'external_id' => 'tt0185906',
                'isfilled' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Escape from Planet Earth',
                'synopsis' => 'Astronaut Scorch Supernova finds himself caught in a trap when he responds to an SOS from a notoriously dangerous alien planet.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTQyMTk4NjkyMl5BMl5BanBnXkFtZTcwMzA2OTY4OA@@._V1_SX300.jpg',
                'actors' => 'Brendan Fraser, Rob Corddry, Ricky Gervais, Jonathan Morgan Heit',
            'producer' => 'Bob Barlen, Cal Brunker, Tony Leech (story), Cory Edwards (story), Stephen Fry (additional story material)',
                'duration_pattern' => 89,
                'external_id' => 'tt0765446',
                'isfilled' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Breaking Bad',
                'synopsis' => 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine, with his former student, in order to secure his family\'s financial future.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTQ0ODYzODc0OV5BMl5BanBnXkFtZTgwMDk3OTcyMDE@._V1_SX300.jpg',
                'actors' => 'Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris',
                'producer' => 'Vince Gilligan',
                'duration_pattern' => 49,
                'external_id' => 'tt0903747',
                'isfilled' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Game of Thrones',
                'synopsis' => 'While a civil war brews between several noble families in Westeros, the children of the former rulers of the land attempt to rise up to power. Meanwhile a forgotten race, bent on destruction, plans to return after thousands of years in the North.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjM5OTQ1MTY5Nl5BMl5BanBnXkFtZTgwMjM3NzMxODE@._V1_SX300.jpg',
                'actors' => 'Peter Dinklage, Lena Headey, Kit Harington, Emilia Clarke',
                'producer' => 'David Benioff, D.B. Weiss',
                'duration_pattern' => 56,
                'external_id' => 'tt0944947',
                'isfilled' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'The Wire',
                'synopsis' => 'Baltimore drug scene, seen through the eyes of drug dealers and law enforcement.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BNjc1NzYwODEyMV5BMl5BanBnXkFtZTcwNTcxMzU1MQ@@._V1_SX300.jpg',
                'actors' => 'Dominic West, John Doman, Deirdre Lovejoy, Wendell Pierce',
                'producer' => 'David Simon',
                'duration_pattern' => 59,
                'external_id' => 'tt0306414',
                'isfilled' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Cosmos: A Spacetime Odyssey',
                'synopsis' => 'A documentary series that explores how we discovered the laws of nature and found our coordinates in space and time.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTc5NzgwNDE3N15BMl5BanBnXkFtZTgwNDAxMTY5MTE@._V1._CR51,41,938,1336_SY132_CR2,0,89,132_AL_.jpg_V1_SX300.jpg',
                'actors' => 'Neil deGrasse Tyson, Carl Sagan',
                'producer' => 'N/A',
                'duration_pattern' => 557,
                'external_id' => 'tt2395695',
                'isfilled' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Cosmos',
                'synopsis' => 'Astronomer Carl Sagan leads us on an engaging guided tour of the various elements and cosmological theories of the universe.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTI0NTg5MjA5OF5BMl5BanBnXkFtZTcwNDMxMTEyMQ@@._V1_SX300.jpg',
                'actors' => 'Carl Sagan',
                'producer' => 'N/A',
                'duration_pattern' => 60,
                'external_id' => 'tt0081846',
                'isfilled' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Rick and Morty',
                'synopsis' => 'An animated series that follows the exploits of a super scientist and his not so bright grandson.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTQxNDEwNTE0Nl5BMl5BanBnXkFtZTgwMzQ1MTg3MDE@._V1_SX300.jpg',
                'actors' => 'Justin Roiland, Chris Parnell, Spencer Grammer, Sarah Chalke',
                'producer' => 'Dan Harmon, Justin Roiland',
                'duration_pattern' => 22,
                'external_id' => 'tt2861424',
                'isfilled' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'The Civil War',
                'synopsis' => 'A comprehensive survey of the American Civil War.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTc0NTY5MzAwOV5BMl5BanBnXkFtZTcwNTk3MzcyMQ@@._V1_SX300.jpg',
                'actors' => 'Sam Waterston, Julie Harris, Jason Robards, Morgan Freeman',
                'producer' => 'N/A',
                'duration_pattern' => 680,
                'external_id' => 'tt0098769',
                'isfilled' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'The Sopranos',
                'synopsis' => 'New Jersey mob boss, Tony Soprano, deals with personal and professional issues in his home and business life.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTIxMjc4NTA2Nl5BMl5BanBnXkFtZTYwNTU2MzU5._V1_SX300.jpg',
                'actors' => 'James Gandolfini, Lorraine Bracco, Edie Falco, Michael Imperioli',
                'producer' => 'David Chase',
                'duration_pattern' => 55,
                'external_id' => 'tt0141842',
                'isfilled' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Young Sherlock Holmes',
                'synopsis' => 'When assorted people start having inexplicable delusions that lead to their deaths, a teenage Sherlock Holmes decides to investigate.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjA0NjMyMTg4NV5BMl5BanBnXkFtZTcwMDIwNTAwMQ@@._V1_SX300.jpg',
                'actors' => 'Nicholas Rowe, Alan Cox, Sophie Ward, Anthony Higgins',
            'producer' => 'Arthur Conan Doyle (characters), Chris Columbus (screenplay), Quico Rovira-Beleta (Castilian Spanish translation & adaptation)',
                'duration_pattern' => 109,
                'external_id' => 'tt0090357',
                'isfilled' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'The World at War',
                'synopsis' => 'A series of documentaries about World War II.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTYyMzQ0NDk4OF5BMl5BanBnXkFtZTcwOTAwNjYyMQ@@._V1_SX300.jpg',
                'actors' => 'Laurence Olivier, Adolf Hitler',
                'producer' => 'N/A',
                'duration_pattern' => 52,
                'external_id' => 'tt0071075',
                'isfilled' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Life',
            'synopsis' => 'The story of wrongfully convicted men (Eddie Murphy and Martin Lawrence) who discover the value of life after serving 65 years in prison.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjAwMTEwMDAwMl5BMl5BanBnXkFtZTcwODk4NDgyMQ@@._V1_SX300.jpg',
                'actors' => 'Eddie Murphy, Martin Lawrence, Obba Babatundé, Nick Cassavetes',
                'producer' => 'Robert Ramsey, Matthew Stone',
                'duration_pattern' => 108,
                'external_id' => 'tt0123964',
                'isfilled' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Avatar: The Last Airbender',
                'synopsis' => 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTM3MTc3OTc0NF5BMl5BanBnXkFtZTcwOTQ0OTM1MQ@@._V1._CR34,0,295,440_SX89_AL_.jpg_V1_SX300.jpg',
                'actors' => 'Zach Tyler, Dee Bradley Baker, Mae Whitman, Jack De Sena',
                'producer' => 'Michael Dante DiMartino, Bryan Konietzko',
                'duration_pattern' => 23,
                'external_id' => 'tt0417299',
                'isfilled' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Last Week Tonight with John Oliver',
                'synopsis' => 'Former Daily Show Correspondent John Oliver brings his persona to this new weekly news satire program.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BNDAwMDY0NjA2Ml5BMl5BanBnXkFtZTgwMTA1NTI3NzE@._V1_SX300.jpg',
                'actors' => 'John Oliver, David Kaye',
                'producer' => 'N/A',
                'duration_pattern' => 30,
                'external_id' => 'tt3530232',
                'isfilled' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'True Detective',
                'synopsis' => 'An anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTUzNTMwODI1OV5BMl5BanBnXkFtZTgwMDIzMTQ0NTE@._V1_SX300.jpg',
                'actors' => 'Matthew McConaughey, Colin Farrell, Woody Harrelson, Rachel McAdams',
                'producer' => 'Nic Pizzolatto',
                'duration_pattern' => 55,
                'external_id' => 'tt2356777',
                'isfilled' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Firefly',
                'synopsis' => 'Five hundred years in the future, a renegade crew aboard a small spacecraft tries to survive as they travel the unknown parts of the galaxy and evade warring factions as well as authority agents out to get them.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTM0OTIzNjM4OV5BMl5BanBnXkFtZTcwNDk4MDU5MQ@@._V1._CR57,54,340,418_SY132_CR9,0,89,132_AL_.jpg_V1_SX300.jpg',
                'actors' => 'Nathan Fillion, Gina Torres, Alan Tudyk, Morena Baccarin',
                'producer' => 'Joss Whedon',
                'duration_pattern' => 44,
                'external_id' => 'tt0303461',
                'isfilled' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Human Planet',
                'synopsis' => 'Like all life forms, humanity partially adapts to types of natural environment, yet also tends to change them. Each episode examines how life differs for men and nature in some type of ...',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTMyMDI0MDI3M15BMl5BanBnXkFtZTcwMTQ5NDQ3NA@@._V1_SX300.jpg',
                'actors' => 'John Hurt',
                'producer' => 'N/A',
                'duration_pattern' => 50,
                'external_id' => 'tt1806234',
                'isfilled' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Golden Earring: Live from The Twilight Zone',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Rinus Gerritsen, Barry Hay, George Kooymans, Cesar Zuiderwijk',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt1332710',
                'isfilled' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Marco Polo',
                'synopsis' => 'In a world replete with greed, betrayal, sexual intrigue and rivalry, "Marco Polo" is based on the famed explorer\'s adventures in Kublai Khan\'s court in 13th century Mongolia.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTcwMDU5NzMzOV5BMl5BanBnXkFtZTgwNzk5NTE0MzE@._V1_SX300.jpg',
                'actors' => 'Benedict Wong, Olivia Cheng, Joan Chen, Zhu Zhu',
                'producer' => 'John Fusco',
                'duration_pattern' => 60,
                'external_id' => 'tt2189461',
                'isfilled' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Marco Polo',
                'synopsis' => 'The life and experiences of the 13th-century explorer, who sought to connect the civilizations of China and Europe through trade.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTU4ODIwMTQzM15BMl5BanBnXkFtZTcwNjgyNDMzMQ@@._V1_SX300.jpg',
                'actors' => 'Ken Marshall, Denholm Elliott, Tony Vogel, David Warner',
                'producer' => 'N/A',
                'duration_pattern' => 504,
                'external_id' => 'tt0083446',
                'isfilled' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Marco',
                'synopsis' => 'In a Little village, in the Pyrenees, lives Marco with his smaller brother Lucas and his mother, Ana...',
                'cover_img_url' => 'N/A',
                'actors' => 'Ariadna Gil, Sergi Méndez, Raúl del Pozo, Juan del Pozo',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt2128000',
                'isfilled' => 0,
            ),
            22 => 
            array (
                'id' => 23,
            'title' => 'The Adventures of Marco & Gina (Sopra i tetti di Venezia)',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'N/A',
                'producer' => 'N/A',
                'duration_pattern' => 26,
                'external_id' => 'tt0275117',
                'isfilled' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'The Travels of the Young Marco Polo',
                'synopsis' => 'In a time when the earth was believed to be flat and there was much to discover, young Marco Polo sets off to find his missing father, who vanished while exploring the Road to China. ...',
                'cover_img_url' => 'N/A',
                'actors' => 'Boris Aljinovic, Paul Aspland, Linus Drews, Elia Francolino',
                'producer' => 'N/A',
                'duration_pattern' => 25,
                'external_id' => 'tt3341090',
                'isfilled' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'La pietra di Marco Polo',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Stefano Cola, Anna Da Malta, Nicola Di Pol, Chiara Doardo',
                'producer' => 'N/A',
                'duration_pattern' => 25,
                'external_id' => 'tt1561888',
                'isfilled' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'Die Marco-Polo-Fährte',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'N/A',
                'producer' => 'N/A',
                'duration_pattern' => 43,
                'external_id' => 'tt1802287',
                'isfilled' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Marco Chow Massage',
                'synopsis' => 'Comedic mock-adult video series following a gay ESL Chinese male massage therapist and his naughty hidden camera adventures -- one of Marco\'s clients will soon hire him as an assistant -- ...',
                'cover_img_url' => 'N/A',
                'actors' => 'Greg Armstrong-Morris, Darren Boquist, Damon Calderwood, Jason Cermak',
                'producer' => 'N/A',
                'duration_pattern' => 5,
                'external_id' => 'tt2502908',
                'isfilled' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Marco Polo: A Very Modern Journey',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Nicolò Agostini, Zhao Qiguang, Ramon Tikaram',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt3997418',
                'isfilled' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Aventuras de Marco Polo',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'N/A',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt0288914',
                'isfilled' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'KVN - Klub Veselikh i Nanodchivikh',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Konstantin Mayer',
                'producer' => 'N/A',
                'duration_pattern' => 110,
                'external_id' => 'tt0470013',
                'isfilled' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Magical Girl Lyrical Nanoha',
                'synopsis' => 'N/A',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BNDQ0NTA1MzA2Ml5BMl5BanBnXkFtZTcwOTg5NjkxMg@@._V1_SX300.jpg',
                'actors' => 'Jennifer Cascio, Jonathan Meza',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt0808082',
                'isfilled' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Nano',
            'synopsis' => 'Nano (short for Manuel) runs an oceanarium, Mundo Marino, in spite of the fact that his father, Noel, wants him to join the family enterprise as is expected of an aristocrat. Nano, an ...',
                'cover_img_url' => 'N/A',
                'actors' => 'Gustavo Bermúdez, Araceli González, Mario Pasik, Lydia Lamaison',
                'producer' => 'N/A',
                'duration_pattern' => 60,
                'external_id' => 'tt0220251',
                'isfilled' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Mahô shôjo ririkaru nanoha: Êsu',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Yukari Tamura, Nana Mizuki, Jennifer Alyx, Bailey Chadwick',
                'producer' => 'Masaki Tsuzuki',
                'duration_pattern' => 0,
                'external_id' => 'tt1159864',
                'isfilled' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Mahô shôjo ririkaru nanoha: Sutoraikâzu',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Nana Mizuki',
                'producer' => 'Masaki Tsuzuki',
                'duration_pattern' => 0,
                'external_id' => 'tt1159863',
                'isfilled' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'L\'ottavo nano',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Serena Dandini, Corrado Guzzanti, Neri Marcorè',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt2198761',
                'isfilled' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Magical Lyrical Girl Nanoha A\'s',
                'synopsis' => 'Several months after Nanoha became a Magical Girl, she is still no able to meet with her close friend, Fate Testarossa, who is being held in the Space/Time Administration Bureau for her ...',
                'cover_img_url' => 'N/A',
                'actors' => 'Patrick Aghajanian',
                'producer' => 'N/A',
                'duration_pattern' => 25,
                'external_id' => 'tt1963222',
                'isfilled' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Nanolyubov',
                'synopsis' => 'A beautiful robot learns to become human.',
                'cover_img_url' => 'N/A',
                'actors' => 'Lyubov Bakhankova',
                'producer' => 'N/A',
                'duration_pattern' => 48,
                'external_id' => 'tt1772607',
                'isfilled' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Nano',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Kristina zur Mühlen, Gerald Hüther, Ingolf Baur, Angela Elis',
                'producer' => 'N/A',
                'duration_pattern' => 30,
                'external_id' => 'tt0465838',
                'isfilled' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'NanoCelentano',
                'synopsis' => 'N/A',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BNDViMjk4NTUtMTg1Mi00YTE2LTk3NDItYTRmZTBiODcxODhmXkEyXkFqcGdeQXVyNTI4MzMxNzg@._V1_SX300.jpg',
                'actors' => 'Benzi Giertz',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt5472698',
                'isfilled' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Arrow',
                'synopsis' => 'Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTg3OTc0NzkyOV5BMl5BanBnXkFtZTgwMDMwMTM3MjE@._V1_SX300.jpg',
                'actors' => 'Stephen Amell, David Ramsey, Willa Holland, Paul Blackthorne',
                'producer' => 'Greg Berlanti, Marc Guggenheim, Andrew Kreisberg',
                'duration_pattern' => 42,
                'external_id' => 'tt2193021',
                'isfilled' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'Arrested Development',
                'synopsis' => 'Level-headed son Michael Bluth takes over family affairs after his father is imprisoned. But the rest of his spoiled, dysfunctional family are making his job unbearable.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTk4OTIyNzA5NF5BMl5BanBnXkFtZTcwODQxMTE1OQ@@._V1_SX300.jpg',
                'actors' => 'Jason Bateman, Portia de Rossi, Will Arnett, Michael Cera',
                'producer' => 'Mitchell Hurwitz',
                'duration_pattern' => 22,
                'external_id' => 'tt0367279',
                'isfilled' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'Two and a Half Men',
                'synopsis' => 'A hedonistic jingle writer\'s free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTcwMDU1MDExNl5BMl5BanBnXkFtZTcwOTAwMjYyOQ@@._V1_SX300.jpg',
                'actors' => 'Jon Cryer, Angus T. Jones, Conchata Ferrell, Charlie Sheen',
                'producer' => 'Lee Aronsohn, Chuck Lorre',
                'duration_pattern' => 22,
                'external_id' => 'tt0369179',
                'isfilled' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'American Horror Story',
                'synopsis' => 'An anthology series that centers on different characters and locations, including a house with a murderous past, an insane asylum, a witch coven, a freak show, and an enigmatic hotel.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTk5ODI1NTA2NF5BMl5BanBnXkFtZTgwODg2NjU4NjE@._V1_SX300.jpg',
                'actors' => 'Evan Peters, Sarah Paulson, Jessica Lange, Denis O\'Hare',
                'producer' => 'Brad Falchuk, Ryan Murphy',
                'duration_pattern' => 60,
                'external_id' => 'tt1844624',
                'isfilled' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'Sons of Anarchy',
                'synopsis' => 'A man in his early 30s struggles to find a balance in his life between being a new dad and his involvement in a motorcycle club.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTEyODg2NzkwMDBeQTJeQWpwZ15BbWU4MDQwODI3MzIx._V1_SX300.jpg',
                'actors' => 'Charlie Hunnam, Katey Sagal, Mark Boone Junior, Kim Coates',
                'producer' => 'Kurt Sutter',
                'duration_pattern' => 45,
                'external_id' => 'tt1124373',
                'isfilled' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'Once Upon a Time',
                'synopsis' => 'A young woman with a troubled past is drawn to a small town in Maine where fairy tales are to be believed.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BODA4ODExNjMyM15BMl5BanBnXkFtZTgwMTcyOTk0ODE@._V1_SX300.jpg',
                'actors' => 'Ginnifer Goodwin, Jennifer Morrison, Lana Parrilla, Josh Dallas',
                'producer' => 'Adam Horowitz, Edward Kitsis',
                'duration_pattern' => 44,
                'external_id' => 'tt1843230',
                'isfilled' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'Grey\'s Anatomy',
                'synopsis' => 'A drama centered on the personal and professional lives of five surgical interns and their supervisors.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjM3NTY5MjMxM15BMl5BanBnXkFtZTgwODk5Mjg5NjE@._V1_SX300.jpg',
                'actors' => 'Ellen Pompeo, Justin Chambers, Chandra Wilson, James Pickens Jr.',
                'producer' => 'Shonda Rhimes',
                'duration_pattern' => 41,
                'external_id' => 'tt0413573',
                'isfilled' => 0,
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'Agents of S.H.I.E.L.D.',
                'synopsis' => 'The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjQxODIwOTIwN15BMl5BanBnXkFtZTgwMjk5Mjg5NjE@._V1_SX300.jpg',
                'actors' => 'Clark Gregg, Ming-Na Wen, Chloe Bennet, Iain De Caestecker',
                'producer' => 'Maurissa Tancharoen, Jed Whedon, Joss Whedon',
                'duration_pattern' => 45,
                'external_id' => 'tt2364582',
                'isfilled' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'It\'s Always Sunny in Philadelphia',
                'synopsis' => 'Four young friends with big egos and slightly arrogant attitudes are the proprietors of an Irish bar in Philadelphia.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTQ1NDg4NjUyM15BMl5BanBnXkFtZTgwMTQ1NTM1NzE@._V1_SX300.jpg',
                'actors' => 'Charlie Day, Glenn Howerton, Rob McElhenney, Kaitlin Olson',
                'producer' => 'Glenn Howerton, Rob McElhenney',
                'duration_pattern' => 22,
                'external_id' => 'tt0472954',
                'isfilled' => 0,
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'Vikings',
                'synopsis' => 'The world of the Vikings is brought to life through the journey of Ragnar Lothbrok, the first Viking to emerge from Norse legend and onto the pages of history - a man on the edge of myth.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BOTEzNzI3MDc0N15BMl5BanBnXkFtZTgwMzk1MzA5NzE@._V1_SX300.jpg',
                'actors' => 'Travis Fimmel, Gustaf Skarsgård, Clive Standen, Katheryn Winnick',
                'producer' => 'Michael Hirst',
                'duration_pattern' => 44,
                'external_id' => 'tt2306299',
                'isfilled' => 0,
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'Vicky the Viking',
                'synopsis' => 'Long ago, in a little Viking Village called Flake, young Wickie lives a happy life. His father, Halvar, is the chief of the Vikings, and would have liked a son a little more courageous. So,...',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjA2MDI1NjQxMl5BMl5BanBnXkFtZTcwNDc1NjI3MQ@@._V1_SX300.jpg',
                'actors' => 'Wolfgang Hess',
                'producer' => 'N/A',
                'duration_pattern' => 23,
                'external_id' => 'tt0278855',
                'isfilled' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'Vikings: Athelstan\'s Journal',
                'synopsis' => 'Viking culture is seen from a first-hand experience through Athelstan\'s perspective. Athelstan reflects his inner thoughts on the ways of the Northmen including all their customs, values, ...',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BYjdjZTE4ZjUtMDhjNi00ODhkLWE5NzktNmVkMDU2NDU2MzdmXkEyXkFqcGdeQXVyNjAyNDQxNjM@._V1_SX300.jpg',
                'actors' => 'George Blagden, Katheryn Winnick, Travis Fimmel, Clive Standen',
                'producer' => 'N/A',
                'duration_pattern' => 4,
                'external_id' => 'tt4622118',
                'isfilled' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'Whale Wars: Viking Shores',
                'synopsis' => 'N/A',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjEzMjM3NDY0Ml5BMl5BanBnXkFtZTgwOTI2NzAxMzE@._V1_SX300.jpg',
                'actors' => 'Simon Ager, Fiona McCuaig, Paul Watson, Whale Wars Viking Shores',
                'producer' => 'N/A',
                'duration_pattern' => 30,
                'external_id' => 'tt2007042',
                'isfilled' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'Vikings',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Neil Oliver',
                'producer' => 'N/A',
                'duration_pattern' => 59,
                'external_id' => 'tt2455488',
                'isfilled' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'title' => 'Blood of the Vikings',
                'synopsis' => 'N/A',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMWQ0MWU4MGUtZWZlYS00NGZlLWJiY2YtNmIzZjZmMTljNDYxXkEyXkFqcGdeQXVyNjQ5NDQxOTY@._V1_SX300.jpg',
                'actors' => 'Elizabeth Keates',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt0410965',
                'isfilled' => 0,
            ),
            54 => 
            array (
                'id' => 55,
                'title' => 'Tales of the Vikings',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Jerome Courtland, Buddy Baer, Walter Barnes, Stefan Schnabel',
                'producer' => 'N/A',
                'duration_pattern' => 30,
                'external_id' => 'tt0053543',
                'isfilled' => 0,
            ),
            55 => 
            array (
                'id' => 56,
                'title' => 'V som i viking',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Micke Dubois',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt0137331',
                'isfilled' => 0,
            ),
            56 => 
            array (
                'id' => 57,
                'title' => 'Vic the Viking',
                'synopsis' => 'Welcome on board the drakkar to sail the seas and share the adventures of our Viking crew. In his home village of Flake or coming alongside far and unknown lands, you will share unique adventures with Vicky.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjM5NDkyMjM3MF5BMl5BanBnXkFtZTgwOTkwNjMyMjE@._V1_SX300.jpg',
                'actors' => 'Lionel Tua, Peter Callan, Paul Davies, Tanguy Goasdoué',
                'producer' => 'Alexs Stadermann',
                'duration_pattern' => 13,
                'external_id' => 'tt3072988',
                'isfilled' => 0,
            ),
            57 => 
            array (
                'id' => 58,
                'title' => 'Viking',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'Toshihiro Itô, Ayako Katô, Takahiro Tazaki, Naoto',
                'producer' => 'N/A',
                'duration_pattern' => 65,
                'external_id' => 'tt3609880',
                'isfilled' => 0,
            ),
            58 => 
            array (
                'id' => 59,
                'title' => 'The Blacklist',
                'synopsis' => 'A new FBI profiler, Elizabeth Keen, has her entire life uprooted when a mysterious criminal, Raymond Reddington, who has eluded capture for decades, turns himself in and insists on speaking only to her.',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTY3NjQ1OTU3NF5BMl5BanBnXkFtZTgwODcwMDI2NjE@._V1_SX300.jpg',
                'actors' => 'James Spader, Megan Boone, Diego Klattenhoff, Harry Lennix',
                'producer' => 'Jon Bokenkamp',
                'duration_pattern' => 43,
                'external_id' => 'tt2741602',
                'isfilled' => 0,
            ),
            59 => 
            array (
                'id' => 60,
                'title' => 'Blacklisted',
                'synopsis' => 'N/A',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMjIyOTkwNjgwM15BMl5BanBnXkFtZTgwNDE3NzM5MzE@._V1_SX300.jpg',
                'actors' => 'Buck Acosta, Arturo Adame, Stephanie Aleman, Anita Altieri',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt2928992',
                'isfilled' => 0,
            ),
            60 => 
            array (
                'id' => 61,
                'title' => 'The Blacklist: 100 Greatest Power Moves',
                'synopsis' => 'Highlighting great moments in African-American history.',
                'cover_img_url' => 'N/A',
                'actors' => 'Arsenio Hall',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt1273282',
                'isfilled' => 0,
            ),
            61 => 
            array (
                'id' => 62,
                'title' => 'Beyond the Blacklist',
                'synopsis' => 'N/A',
                'cover_img_url' => 'N/A',
                'actors' => 'N/A',
                'producer' => 'N/A',
                'duration_pattern' => 4,
                'external_id' => 'tt3262014',
                'isfilled' => 0,
            ),
            62 => 
            array (
                'id' => 63,
                'title' => 'The Blacklist: Redemption',
                'synopsis' => 'N/A',
                'cover_img_url' => 'http://ia.media-imdb.com/images/M/MV5BMTc0ODY1NjU5OF5BMl5BanBnXkFtZTgwMDY5ODE5ODE@._V1_SX300.jpg',
                'actors' => 'Famke Janssen',
                'producer' => 'N/A',
                'duration_pattern' => 0,
                'external_id' => 'tt5592230',
                'isfilled' => 0,
            ),
        ));
        
        
    }
}
